import {
 Building2,
 CalendarDays,
 ContactRound,
 FileText,
 FolderKanban,
 Package,
 Settings,
 ShieldCheck,
 UsersRound,
 WalletCards,
} from "lucide-react";
import type { AdminModule } from "./admin.types";

const fullPermissions = ["view", "create", "edit", "delete", "export", "restore", "manage"] as const;
const standardPermissions = ["view", "create", "edit", "delete", "export"] as const;

export const adminModules: AdminModule[] = [
 {
 id: "employees",
 label: "Users & Employees",
 description: "Manage login access, employee profiles, departments, and employment state from one place.",
 icon: UsersRound,
 permissions: [...fullPermissions],
 fields: [
 { key: "name", label: "Name", type: "text", required: true },
 { key: "email", label: "Email", type: "email", required: true },
 {
 key: "role",
 label: "Role",
 type: "select",
 options: ["Owner", "Administrator", "Manager", "HR", "Finance", "Sales", "Support", "Developer", "Employee", "Guest"],
 required: true,
 },
 { key: "department", label: "Department", type: "select", options: ["Executive", "Engineering", "Product", "Design", "Operations", "Human Resources", "Finance", "Sales", "Customer Success", "Unassigned"] },
 { key: "designation", label: "Designation", type: "text" },
 { key: "status", label: "Status", type: "select", options: ["Active", "On Leave", "Inactive", "Suspended", "Pending"], required: true },
 { key: "joiningDate", label: "Joining Date", type: "date" },
 { key: "lastLogin", label: "Last Login", type: "date" },
 ],
 records: [],
 },
 {
 id: "projects",
 label: "Projects",
 description: "Control project records, ownership, budget, and status.",
 icon: FolderKanban,
 permissions: [...standardPermissions],
 fields: [
 { key: "name", label: "Project Name", type: "text", required: true },
 { key: "manager", label: "Manager", type: "text" },
 { key: "status", label: "Status", type: "select", options: ["Planning", "Active", "On Hold", "Completed", "Delayed"] },
 { key: "budget", label: "Budget", type: "number" },
 { key: "deadline", label: "Deadline", type: "date" },
 ],
 records: [],
 },
 {
 id: "customers",
 label: "Customers",
 description: "Manage CRM customer accounts, health, and revenue ownership.",
 icon: ContactRound,
 permissions: [...standardPermissions],
 fields: [
 { key: "name", label: "Customer", type: "text", required: true },
 { key: "company", label: "Company", type: "text" },
 { key: "owner", label: "Owner", type: "text" },
 { key: "revenue", label: "Revenue", type: "number" },
 { key: "health", label: "Health", type: "select", options: ["Excellent", "Good", "At Risk"] },
 ],
 records: [],
 },
 {
 id: "products",
 label: "Products",
 description: "Manage products, inventory, suppliers, and SKU records.",
 icon: Package,
 permissions: [...standardPermissions],
 fields: [
 { key: "name", label: "Product", type: "text", required: true },
 { key: "sku", label: "SKU", type: "text" },
 { key: "category", label: "Category", type: "select", options: ["Software", "Hardware", "Services", "Subscriptions", "Add-ons"] },
 { key: "price", label: "Price", type: "number" },
 { key: "stock", label: "Stock", type: "number" },
 ],
 records: [],
 },
 {
 id: "documents",
 label: "Documents",
 description: "Manage files, tags, sharing, and permission states.",
 icon: FileText,
 permissions: [...standardPermissions],
 fields: [
 { key: "name", label: "Document", type: "text", required: true },
 { key: "type", label: "Type", type: "select", options: ["PDF", "DOCX", "XLSX", "PPTX", "Image"] },
 { key: "owner", label: "Owner", type: "text" },
 { key: "permission", label: "Permission", type: "select", options: ["Private", "Shared", "Restricted"] },
 { key: "tags", label: "Tags", type: "tags" },
 ],
 records: [],
 },
 {
 id: "meetings",
 label: "Meetings",
 description: "Manage meeting schedules, links, participants, and status.",
 icon: CalendarDays,
 permissions: [...standardPermissions],
 fields: [
 { key: "title", label: "Title", type: "text", required: true },
 { key: "organizer", label: "Organizer", type: "text" },
 { key: "date", label: "Date", type: "date" },
 { key: "status", label: "Status", type: "select", options: ["Scheduled", "In Progress", "Completed", "Cancelled"] },
 { key: "link", label: "Meeting Link", type: "text" },
 ],
 records: [],
 },
 {
 id: "finance",
 label: "Finance",
 description: "Manage finance records, invoices, payments, taxes, and budgets.",
 icon: WalletCards,
 permissions: [...standardPermissions, "restore"],
 fields: [
 { key: "name", label: "Record", type: "text", required: true },
 { key: "type", label: "Type", type: "select", options: ["Income", "Expense", "Invoice", "Payment", "Tax", "Budget"] },
 { key: "amount", label: "Amount", type: "number" },
 { key: "status", label: "Status", type: "select", options: ["Draft", "Pending", "Paid", "Approved", "Filed"] },
 { key: "date", label: "Date", type: "date" },
 ],
 records: [],
 },
 {
 id: "settings",
 label: "Settings",
 description: "Manage application, company, security, and email configuration.",
 icon: Settings,
 permissions: [...fullPermissions],
 fields: [
 { key: "name", label: "Setting", type: "text", required: true },
 { key: "group", label: "Group", type: "select", options: ["Theme", "Company", "Email", "Security"] },
 { key: "value", label: "Value", type: "text" },
 { key: "status", label: "Status", type: "select", options: ["Active", "Disabled", "Needs Review"] },
 ],
 records: [],
 },
];

export const adminSystemCards = [
 { label: "Managed Modules", value: String(adminModules.length), icon: Building2 },
 { label: "API-Backed Modules", value: "1", icon: ShieldCheck },
];
