import type { Integration, IntegrationLog } from "./integrations.types";

export const integrationCategories = ["communication", "crm", "finance", "productivity", "storage", "ai", "other"] as const;

export const seedIntegrations: Integration[] = [
  {
    id: "int-1",
    name: "Slack",
    description: "Team communication and notifications",
    category: "communication",
    status: "connected",
    icon: "MessageSquare",
    connectedAt: "2026-06-10T08:00:00Z",
    lastSyncAt: "2026-07-21T09:30:00Z",
    config: { channel: "#general", notifyOn: ["project_created", "invoice_paid"] },
  },
  {
    id: "int-2",
    name: "Salesforce",
    description: "CRM synchronization and lead management",
    category: "crm",
    status: "connected",
    icon: "ContactRound",
    connectedAt: "2026-05-22T10:00:00Z",
    lastSyncAt: "2026-07-21T08:15:00Z",
    config: { syncDirection: "bidirectional", objects: ["Lead", "Contact", "Opportunity"] },
  },
  {
    id: "int-3",
    name: "QuickBooks",
    description: "Accounting and expense tracking",
    category: "finance",
    status: "error",
    icon: "WalletCards",
    connectedAt: "2026-04-15T07:00:00Z",
    lastSyncAt: "2026-07-20T18:45:00Z",
    config: { companyId: "QB-2026", syncInvoices: true },
  },
  {
    id: "int-4",
    name: "Google Drive",
    description: "Document storage and collaboration",
    category: "storage",
    status: "connected",
    icon: "FileText",
    connectedAt: "2026-03-01T09:00:00Z",
    lastSyncAt: "2026-07-21T07:00:00Z",
    config: { folderId: "AI-BOS-Docs", autoUpload: true },
  },
  {
    id: "int-5",
    name: "OpenAI",
    description: "AI model access and embeddings",
    category: "ai",
    status: "connected",
    icon: "Bot",
    connectedAt: "2026-02-10T06:00:00Z",
    lastSyncAt: "2026-07-21T10:00:00Z",
    config: { model: "gpt-4o-mini", temperature: 0.2 },
  },
  {
    id: "int-6",
    name: "Zoom",
    description: "Video conferencing and meeting recordings",
    category: "communication",
    status: "disconnected",
    icon: "Video",
    connectedAt: undefined,
    lastSyncAt: undefined,
    config: { autoRecord: false },
  },
];

export const seedIntegrationLogs: IntegrationLog[] = [
  { id: "log-1", integrationId: "int-1", action: "sync", status: "success", message: "Synced 12 new messages", timestamp: "2026-07-21T09:30:00Z" },
  { id: "log-2", integrationId: "int-2", action: "sync", status: "success", message: "Synced 3 new leads", timestamp: "2026-07-21T08:15:00Z" },
  { id: "log-3", integrationId: "int-3", action: "sync", status: "failed", message: "API rate limit exceeded", timestamp: "2026-07-20T18:45:00Z" },
  { id: "log-4", integrationId: "int-4", action: "upload", status: "success", message: "Uploaded 5 documents", timestamp: "2026-07-21T07:00:00Z" },
  { id: "log-5", integrationId: "int-5", action: "health_check", status: "success", message: "All systems operational", timestamp: "2026-07-21T10:00:00Z" },
];
