import type { Meeting, MeetingType } from "./meetings.types";

export const meetingTypes: MeetingType[] = ["Internal", "Client", "Sales", "Project", "Leadership"];
export const meetingParticipants = ["Priya Sharma", "Sneha Joshi", "Karan Malhotra", "Neha Reddy", "Vikram Nair", "Ananya Iyer"];

export const seedMeetings: Meeting[] = [
 {
 id: "meeting-1",
 title: "Leadership Standup",
 type: "Leadership",
 date: "2026-07-18",
 startTime: "10:00",
 endTime: "10:30",
 status: "Completed",
 organizer: "Priya Sharma",
 participants: ["Priya Sharma", "Vikram Nair", "Karan Malhotra"],
 agenda: ["Review operating KPIs", "Resolve project blockers", "Confirm weekly priorities"],
 notes: "Revenue trend is strong. Finance automation needs a risk review before release.",
 actionItems: [
 { id: "act-1", title: "Send operating scorecard", owner: "Priya Sharma", dueDate: "2026-07-18", done: true },
 { id: "act-2", title: "Prepare finance risk summary", owner: "Vikram Nair", dueDate: "2026-07-19", done: false },
 ],
 attachments: [{ name: "weekly-scorecard.pdf", type: "PDF", size: "1.1 MB" }],
 zoomLink: "https://zoom.us/j/2026071801",
 googleMeetLink: "https://meet.google.com/aibos-leadership",
 },
 {
 id: "meeting-2",
 title: "Project Risk Review",
 type: "Project",
 date: "2026-07-18",
 startTime: "12:30",
 endTime: "13:15",
 status: "Scheduled",
 organizer: "Sneha Joshi",
 participants: ["Sneha Joshi", "Neha Reddy", "Priya Sharma"],
 agenda: ["Review delayed project list", "Assign action owners", "Update delivery timeline"],
 notes: "Focus on AI Sales Copilot and Finance Automation dependencies.",
 actionItems: [
 { id: "act-3", title: "Update dependency tracker", owner: "Neha Reddy", dueDate: "2026-07-19", done: false },
 ],
 attachments: [{ name: "risk-board.xlsx", type: "XLSX", size: "420 KB" }],
 zoomLink: "https://zoom.us/j/2026071802",
 googleMeetLink: "https://meet.google.com/aibos-risk",
 },
 {
 id: "meeting-3",
 title: "Customer Pipeline Sync",
 type: "Sales",
 date: "2026-07-18",
 startTime: "15:00",
 endTime: "15:45",
 status: "Scheduled",
 organizer: "Karan Malhotra",
 participants: ["Karan Malhotra", "Priya Sharma", "Sneha Joshi"],
 agenda: ["Review qualified leads", "Prioritize proposal follow ups", "Plan renewal calls"],
 notes: "Orbit Finance proposal needs security responses before Tuesday.",
 actionItems: [
 { id: "act-4", title: "Send Orbit security answers", owner: "Priya Sharma", dueDate: "2026-07-21", done: false },
 { id: "act-5", title: "Schedule Nova demo", owner: "Karan Malhotra", dueDate: "2026-07-20", done: false },
 ],
 attachments: [],
 zoomLink: "https://zoom.us/j/2026071803",
 googleMeetLink: "https://meet.google.com/aibos-pipeline",
 },
 {
 id: "meeting-4",
 title: "Finance Automation Demo",
 type: "Client",
 date: "2026-07-19",
 startTime: "17:00",
 endTime: "18:00",
 status: "Scheduled",
 organizer: "Vikram Nair",
 participants: ["Vikram Nair", "Karan Malhotra", "Priya Sharma"],
 agenda: ["Demo invoice approvals", "Walk through audit logs", "Capture customer feedback"],
 notes: "Prepare sandbox data and demo finance dashboard before the call.",
 actionItems: [
 { id: "act-6", title: "Prepare sandbox invoices", owner: "Vikram Nair", dueDate: "2026-07-19", done: false },
 ],
 attachments: [{ name: "demo-script.docx", type: "DOCX", size: "210 KB" }],
 zoomLink: "https://zoom.us/j/2026071901",
 googleMeetLink: "https://meet.google.com/aibos-finance-demo",
 },
 {
 id: "meeting-5",
 title: "Employee Portal Planning",
 type: "Internal",
 date: "2026-07-22",
 startTime: "11:30",
 endTime: "12:15",
 status: "Scheduled",
 organizer: "Ananya Iyer",
 participants: ["Ananya Iyer", "Neha Reddy", "Priya Sharma"],
 agenda: ["Review HR requirements", "Confirm document permissions", "Plan profile workflow"],
 notes: "Tie profile module with onboarding document management.",
 actionItems: [],
 attachments: [],
 zoomLink: "https://zoom.us/j/2026072201",
 googleMeetLink: "https://meet.google.com/aibos-employee-portal",
 },
];
