import type { Task, TaskPriority, TaskStatus } from "./tasks.types";

export const taskStatuses: TaskStatus[] = ["Todo", "In Progress", "Review", "Testing", "Completed"];
export const taskPriorities: TaskPriority[] = ["Low", "Medium", "High", "Critical"];
export const taskLabels = ["Frontend", "Backend", "AI", "CRM", "Finance", "HR", "Bug", "Design", "Automation"];
export const teamMembers = ["Priya Sharma", "Sneha Joshi", "Neha Reddy", "Karan Malhotra", "Vikram Nair", "Ananya Iyer"];

export const seedTasks: Task[] = [
  {
    id: "task-1",
    taskCode: "TSK-2026-001",
    title: "Build AI task summary panel",
    description: "Create the operating summary block for active tasks, risk flags, and next actions.",
    status: "In Progress",
    priority: "High",
    labels: ["AI", "Frontend"],
    assignee: "Sneha Joshi",
    reporter: "Priya Sharma",
    dueDate: "2026-07-24",
    startDate: "2026-07-15",
    estimatedHours: 18,
    actualHours: 9,
    attachments: [{ name: "task-summary-wireframe.png", type: "Image", size: "680 KB" }],
    comments: [{ id: "c-1", author: "Priya Sharma", message: "Keep the panel scannable for managers.", createdAt: "2026-07-18" }],
    checklist: [
      { id: "cl-1", title: "Create cards", done: true },
      { id: "cl-2", title: "Connect task metrics", done: false },
      { id: "cl-3", title: "Review responsive layout", done: false },
    ],
    recurring: false,
    recurrence: "None",
    activityLogs: [
      { id: "a-1", title: "Status changed to In Progress", time: "Today" },
      { id: "a-2", title: "Wireframe attached", time: "Yesterday" },
    ],
    notifications: ["Due in 6 days", "Assignee updated"],
    timeEntries: [{ id: "te-1", user: "Sneha Joshi", hours: 3, note: "Component build", createdAt: "2026-07-18" }],
    createdAt: "2026-07-14",
    updatedAt: "2026-07-18",
  },
  {
    id: "task-2",
    taskCode: "TSK-2026-002",
    title: "Review finance approval workflow",
    description: "Validate approval steps, notification events, and fallback permissions for expense reviews.",
    status: "Review",
    priority: "Critical",
    labels: ["Finance", "Automation"],
    assignee: "Vikram Nair",
    reporter: "Karan Malhotra",
    dueDate: "2026-07-21",
    startDate: "2026-07-12",
    estimatedHours: 24,
    actualHours: 19,
    attachments: [{ name: "approval-flow.pdf", type: "PDF", size: "1.2 MB" }],
    comments: [{ id: "c-2", author: "Karan Malhotra", message: "Security review is required before launch.", createdAt: "2026-07-17" }],
    checklist: [
      { id: "cl-4", title: "Map approver roles", done: true },
      { id: "cl-5", title: "Validate escalations", done: true },
      { id: "cl-6", title: "Sign off controls", done: false },
    ],
    recurring: true,
    recurrence: "Weekly",
    activityLogs: [{ id: "a-3", title: "Moved to Review", time: "2 hr ago" }],
    notifications: ["Critical priority", "Review pending"],
    timeEntries: [{ id: "te-2", user: "Vikram Nair", hours: 4, note: "Workflow validation", createdAt: "2026-07-17" }],
    createdAt: "2026-07-11",
    updatedAt: "2026-07-18",
  },
  {
    id: "task-3",
    taskCode: "TSK-2026-003",
    title: "QA responsive dashboard cards",
    description: "Test dashboard cards across mobile, tablet, and desktop breakpoints.",
    status: "Testing",
    priority: "Medium",
    labels: ["Frontend", "Bug"],
    assignee: "Neha Reddy",
    reporter: "Priya Sharma",
    dueDate: "2026-07-26",
    startDate: "2026-07-18",
    estimatedHours: 10,
    actualHours: 4,
    attachments: [],
    comments: [],
    checklist: [
      { id: "cl-7", title: "Mobile pass", done: true },
      { id: "cl-8", title: "Desktop pass", done: false },
    ],
    recurring: false,
    recurrence: "None",
    activityLogs: [{ id: "a-4", title: "Testing started", time: "Today" }],
    notifications: ["Testing assigned"],
    timeEntries: [],
    createdAt: "2026-07-18",
    updatedAt: "2026-07-18",
  },
  {
    id: "task-4",
    taskCode: "TSK-2026-004",
    title: "Prepare CRM import checklist",
    description: "Create customer import checklist for validation, duplicate handling, and owner mapping.",
    status: "Todo",
    priority: "Low",
    labels: ["CRM", "Documents"],
    assignee: "Karan Malhotra",
    reporter: "Sneha Joshi",
    dueDate: "2026-08-02",
    startDate: "2026-07-25",
    estimatedHours: 8,
    actualHours: 0,
    attachments: [],
    comments: [],
    checklist: [
      { id: "cl-9", title: "Define required fields", done: false },
      { id: "cl-10", title: "Add sample CSV", done: false },
    ],
    recurring: false,
    recurrence: "None",
    activityLogs: [{ id: "a-5", title: "Task created", time: "Yesterday" }],
    notifications: ["Starts next week"],
    timeEntries: [],
    createdAt: "2026-07-17",
    updatedAt: "2026-07-17",
  },
  {
    id: "task-5",
    taskCode: "TSK-2026-005",
    title: "Publish onboarding policy update",
    description: "Update employee onboarding documents with new security and device setup steps.",
    status: "Completed",
    priority: "Medium",
    labels: ["HR", "Documents"],
    assignee: "Ananya Iyer",
    reporter: "Priya Sharma",
    dueDate: "2026-07-16",
    startDate: "2026-07-08",
    estimatedHours: 12,
    actualHours: 11,
    attachments: [{ name: "onboarding-policy.docx", type: "Document", size: "740 KB" }],
    comments: [{ id: "c-3", author: "Ananya Iyer", message: "Published for all new employees.", createdAt: "2026-07-16" }],
    checklist: [
      { id: "cl-11", title: "Policy copy", done: true },
      { id: "cl-12", title: "Leadership approval", done: true },
    ],
    recurring: true,
    recurrence: "Monthly",
    activityLogs: [{ id: "a-6", title: "Completed", time: "Jul 16" }],
    notifications: ["Completed"],
    timeEntries: [{ id: "te-3", user: "Ananya Iyer", hours: 2, note: "Final publish", createdAt: "2026-07-16" }],
    createdAt: "2026-07-08",
    updatedAt: "2026-07-16",
  },
];
