import type { AttendanceRecord, Designation, Employee, Holiday, LeaveRequest } from "./employees.types";

export const designations: Designation[] = [
 { title: "Founder & CEO", department: "Executive", level: "L8", employees: 1 },
 { title: "Head of Business Operations", department: "Operations", level: "L6", employees: 1 },
 { title: "Product Delivery Manager", department: "Product", level: "L5", employees: 1 },
 { title: "People Operations Lead", department: "Human Resources", level: "L4", employees: 1 },
 { title: "Finance Controller", department: "Finance", level: "L4", employees: 1 },
 { title: "Enterprise Account Executive", department: "Sales", level: "L4", employees: 1 },
 { title: "Customer Success Lead", department: "Customer Success", level: "L4", employees: 1 },
 { title: "Senior Backend Engineer", department: "Engineering", level: "L5", employees: 1 },
 { title: "Frontend Engineer", department: "Engineering", level: "L3", employees: 1 },
 { title: "QA Automation Engineer", department: "Engineering", level: "L3", employees: 1 },
 { title: "DevOps Engineer", department: "Engineering", level: "L4", employees: 1 },
 { title: "Product Designer", department: "Design", level: "L3", employees: 1 },
 { title: "Junior Software Engineer", department: "Engineering", level: "L2", employees: 1 },
 { title: "Sales Development Representative", department: "Sales", level: "L2", employees: 1 },
 { title: "Implementation Specialist", department: "Customer Success", level: "L3", employees: 1 },
 { title: "Growth Marketing Associate", department: "Marketing", level: "L2", employees: 1 },
 { title: "IT & Office Coordinator", department: "Operations", level: "L2", employees: 1 },
 { title: "External Security Auditor", department: "Executive", level: "L1", employees: 1 },
];

export const holidays: Holiday[] = [
 { name: "Nexora Foundation Day", date: "2026-04-03", type: "Company" },
 { name: "Independence Day", date: "2026-08-15", type: "National" },
 { name: "Diwali", date: "2026-11-08", type: "Festival" },
 { name: "Year End Break", date: "2026-12-25", type: "Company" },
];

type EmployeeSeed = Pick<
 Employee,
 "id" | "employeeCode" | "name" | "email" | "department" | "designation" | "employmentType" | "joiningDate" | "status" | "skills" | "performanceScore"
> & {
 annualCtc: number;
 location?: string;
};

function initials(name: string) {
 return name
 .split(" ")
 .filter(Boolean)
 .slice(0, 2)
 .map((part) => part[0]?.toUpperCase() ?? "")
 .join("");
}

function makeEmployee(seed: EmployeeSeed): Employee {
 const phoneSuffix = seed.employeeCode.slice(-3);
 return {
 ...seed,
 avatar: initials(seed.name),
 phone: `+91 80 4567 ${phoneSuffix}`,
 location: seed.location ?? "Bengaluru, India",
 role: "Employee",
 personalInformation: {
 dateOfBirth: "Not added",
 gender: "Not added",
 nationality: "Indian",
 maritalStatus: "Not added",
 },
 contact: {
 address: seed.location ?? "Bengaluru, India",
 emergencyContact: `+91 80 5567 ${phoneSuffix}`,
 },
 experience: [`${seed.designation} at Nexora Softworks`],
 education: ["Not added"],
 documents: [{ name: `${seed.employeeCode.toLowerCase()}-profile.pdf`, type: "HR", size: "320 KB" }],
 salaryDetails: {
 annualCtc: seed.annualCtc,
 monthlySalary: Math.round(seed.annualCtc / 12),
 bank: "HDFC Bank",
 taxId: "Not added",
 },
 };
}

export const seedEmployees: Employee[] = [
 makeEmployee({
 id: "emp-1",
 employeeCode: "NEX-2026-001",
 name: "Aarav Mehta",
 email: "aarav.mehta@nexorasoftworks.dev",
 department: "Executive",
 designation: "Founder & CEO",
 employmentType: "Full Time",
 joiningDate: "2026-01-15",
 status: "Active",
 skills: ["Strategy", "AI Governance", "Enterprise Sales"],
 annualCtc: 9800000,
 performanceScore: 97,
 }),
 makeEmployee({
 id: "emp-2",
 employeeCode: "NEX-2026-002",
 name: "Isha Sinha",
 email: "isha.sinha@nexorasoftworks.dev",
 department: "Operations",
 designation: "Head of Business Operations",
 employmentType: "Full Time",
 joiningDate: "2026-01-20",
 status: "Active",
 skills: ["RBAC", "Security", "Operations"],
 annualCtc: 4200000,
 performanceScore: 94,
 }),
 makeEmployee({
 id: "emp-3",
 employeeCode: "NEX-2026-003",
 name: "Kabir Arora",
 email: "kabir.arora@nexorasoftworks.dev",
 department: "Product",
 designation: "Product Delivery Manager",
 employmentType: "Full Time",
 joiningDate: "2026-01-27",
 status: "Active",
 skills: ["Delivery", "Agile", "Product Strategy"],
 annualCtc: 3600000,
 performanceScore: 92,
 }),
 makeEmployee({
 id: "emp-4",
 employeeCode: "NEX-2026-004",
 name: "Naina Rao",
 email: "naina.rao@nexorasoftworks.dev",
 department: "Human Resources",
 designation: "People Operations Lead",
 employmentType: "Full Time",
 joiningDate: "2026-02-03",
 status: "Active",
 skills: ["Onboarding", "Policies", "Payroll"],
 annualCtc: 2400000,
 performanceScore: 91,
 }),
 makeEmployee({
 id: "emp-5",
 employeeCode: "NEX-2026-005",
 name: "Devika Menon",
 email: "devika.menon@nexorasoftworks.dev",
 department: "Finance",
 designation: "Finance Controller",
 employmentType: "Full Time",
 joiningDate: "2026-02-10",
 status: "Active",
 skills: ["FP&A", "Compliance", "Budgeting"],
 annualCtc: 2800000,
 performanceScore: 89,
 }),
 makeEmployee({
 id: "emp-6",
 employeeCode: "NEX-2026-006",
 name: "Rhea Kapoor",
 email: "rhea.kapoor@nexorasoftworks.dev",
 department: "Sales",
 designation: "Enterprise Account Executive",
 employmentType: "Full Time",
 joiningDate: "2026-02-18",
 status: "Active",
 skills: ["CRM", "Forecasting", "Negotiation"],
 annualCtc: 2600000,
 performanceScore: 90,
 }),
 makeEmployee({
 id: "emp-7",
 employeeCode: "NEX-2026-007",
 name: "Manav Bansal",
 email: "manav.bansal@nexorasoftworks.dev",
 department: "Customer Success",
 designation: "Customer Success Lead",
 employmentType: "Full Time",
 joiningDate: "2026-03-02",
 status: "Active",
 skills: ["Support", "Escalation", "Customer Health"],
 annualCtc: 2200000,
 performanceScore: 88,
 }),
 makeEmployee({
 id: "emp-8",
 employeeCode: "NEX-2026-008",
 name: "Tara Kulkarni",
 email: "tara.kulkarni@nexorasoftworks.dev",
 department: "Engineering",
 designation: "Senior Backend Engineer",
 employmentType: "Full Time",
 joiningDate: "2026-03-09",
 status: "Active",
 skills: ["Node.js", "MongoDB", "Architecture"],
 annualCtc: 3800000,
 performanceScore: 93,
 }),
 makeEmployee({
 id: "emp-9",
 employeeCode: "NEX-2026-009",
 name: "Omar Qureshi",
 email: "omar.qureshi@nexorasoftworks.dev",
 department: "Engineering",
 designation: "Frontend Engineer",
 employmentType: "Full Time",
 joiningDate: "2026-03-16",
 status: "Active",
 skills: ["React", "TypeScript", "Accessibility"],
 annualCtc: 2700000,
 performanceScore: 87,
 }),
 makeEmployee({
 id: "emp-10",
 employeeCode: "NEX-2026-010",
 name: "Saanvi Iyer",
 email: "saanvi.iyer@nexorasoftworks.dev",
 department: "Engineering",
 designation: "QA Automation Engineer",
 employmentType: "Full Time",
 joiningDate: "2026-03-23",
 status: "Active",
 skills: ["Playwright", "API Testing", "Regression"],
 annualCtc: 2100000,
 performanceScore: 86,
 }),
 makeEmployee({
 id: "emp-11",
 employeeCode: "NEX-2026-011",
 name: "Vihaan Shah",
 email: "vihaan.shah@nexorasoftworks.dev",
 department: "Engineering",
 designation: "DevOps Engineer",
 employmentType: "Full Time",
 joiningDate: "2026-04-01",
 status: "Active",
 skills: ["CI/CD", "Docker", "Monitoring"],
 annualCtc: 3000000,
 performanceScore: 89,
 }),
 makeEmployee({
 id: "emp-12",
 employeeCode: "NEX-2026-012",
 name: "Maya Fernandes",
 email: "maya.fernandes@nexorasoftworks.dev",
 department: "Design",
 designation: "Product Designer",
 employmentType: "Full Time",
 joiningDate: "2026-04-08",
 status: "Active",
 skills: ["UX", "Design Systems", "Research"],
 annualCtc: 2300000,
 performanceScore: 88,
 }),
 makeEmployee({
 id: "emp-13",
 employeeCode: "NEX-2026-013",
 name: "Arjun Nair",
 email: "arjun.nair@nexorasoftworks.dev",
 department: "Engineering",
 designation: "Junior Software Engineer",
 employmentType: "Full Time",
 joiningDate: "2026-04-15",
 status: "Active",
 skills: ["JavaScript", "APIs", "Debugging"],
 annualCtc: 1400000,
 performanceScore: 82,
 }),
 makeEmployee({
 id: "emp-14",
 employeeCode: "NEX-2026-014",
 name: "Simran Gill",
 email: "simran.gill@nexorasoftworks.dev",
 department: "Sales",
 designation: "Sales Development Representative",
 employmentType: "Full Time",
 joiningDate: "2026-05-04",
 status: "Active",
 skills: ["Prospecting", "CRM", "Demos"],
 annualCtc: 1300000,
 performanceScore: 84,
 }),
 makeEmployee({
 id: "emp-15",
 employeeCode: "NEX-2026-015",
 name: "Pranav Desai",
 email: "pranav.desai@nexorasoftworks.dev",
 department: "Customer Success",
 designation: "Implementation Specialist",
 employmentType: "Full Time",
 joiningDate: "2026-05-12",
 status: "Active",
 skills: ["Onboarding", "Integrations", "Training"],
 annualCtc: 1600000,
 performanceScore: 85,
 }),
 makeEmployee({
 id: "emp-16",
 employeeCode: "NEX-2026-016",
 name: "Zoya Khan",
 email: "zoya.khan@nexorasoftworks.dev",
 department: "Marketing",
 designation: "Growth Marketing Associate",
 employmentType: "Full Time",
 joiningDate: "2026-06-01",
 status: "Active",
 skills: ["Content", "Campaigns", "Analytics"],
 annualCtc: 1200000,
 performanceScore: 83,
 }),
 makeEmployee({
 id: "emp-17",
 employeeCode: "NEX-2026-017",
 name: "Ethan Dsouza",
 email: "ethan.dsouza@nexorasoftworks.dev",
 department: "Operations",
 designation: "IT & Office Coordinator",
 employmentType: "Full Time",
 joiningDate: "2026-06-15",
 status: "On Leave",
 skills: ["IT Assets", "Office Ops", "Vendor Coordination"],
 annualCtc: 1100000,
 performanceScore: 80,
 }),
 makeEmployee({
 id: "emp-18",
 employeeCode: "NEX-2026-018",
 name: "Leena Thomas",
 email: "leena.thomas@nexorasoftworks.dev",
 department: "Executive",
 designation: "External Security Auditor",
 employmentType: "Contract",
 joiningDate: "2026-07-01",
 status: "Active",
 skills: ["Security Review", "Compliance", "Audit"],
 annualCtc: 0,
 performanceScore: 78,
 }),
];

export const seedAttendance: AttendanceRecord[] = [
 { id: "att-1", employeeId: "emp-1", date: "2026-07-24", checkIn: "09:05", checkOut: "18:10", workingHours: 9.1, status: "Present" },
 { id: "att-2", employeeId: "emp-2", date: "2026-07-24", checkIn: "09:00", checkOut: "17:55", workingHours: 8.9, status: "Present" },
 { id: "att-3", employeeId: "emp-3", date: "2026-07-24", checkIn: "09:20", workingHours: 5.2, status: "Present" },
 { id: "att-8", employeeId: "emp-8", date: "2026-07-24", checkIn: "09:15", checkOut: "18:30", workingHours: 9.25, status: "Present" },
 { id: "att-17", employeeId: "emp-17", date: "2026-07-24", workingHours: 0, status: "On Leave" },
];

export const seedLeaveRequests: LeaveRequest[] = [
 { id: "leave-1", employeeId: "emp-17", type: "Sick Leave", from: "2026-07-24", to: "2026-07-26", reason: "Medical recovery", status: "Approved", approver: "Naina Rao" },
 { id: "leave-2", employeeId: "emp-14", type: "Paid Leave", from: "2026-08-05", to: "2026-08-08", reason: "Family travel", status: "Pending", approver: "Naina Rao" },
];
