import { AppError } from "../utils/app-error.js";
import { decryptBiometricTemplate } from "../utils/crypto.js";

export type FaceDescriptorQuality = {
  faceScore: number;
  real: number;
  live: number;
  faceSize: number;
  pose: { roll: number; yaw: number; pitch: number } | null;
};

export type FaceDescriptorSample = {
  embedding: number[];
  quality: FaceDescriptorQuality;
};

export type FaceEnrollmentTemplate = {
  provider: string;
  templateVersion: string;
  template: string;
  qualityChecks: FaceDescriptorQuality[];
};

export type FaceVerificationResult = {
  matched: boolean;
  similarity: number;
  modelVersion: string;
};

export interface FaceRecognitionProvider {
  readonly name: string;
  readonly modelVersion: string;
  enroll(samples: FaceDescriptorSample[]): Promise<FaceEnrollmentTemplate>;
  verify(embedding: number[], encryptedTemplate: string): Promise<FaceVerificationResult>;
}

type HumanFaceResTemplate = {
  provider: string;
  templateVersion: string;
  descriptor: number[];
  descriptorLength: number;
  createdAt: string;
};

const MATCH_THRESHOLD = 0.5;
const ENROLLMENT_CONSISTENCY_THRESHOLD = 0.45;

function assertDescriptor(descriptor: number[], expectedLength?: number) {
  if (
    !Array.isArray(descriptor) ||
    descriptor.length < 128 ||
    descriptor.length > 2048 ||
    descriptor.some((value) => !Number.isFinite(value) || Math.abs(value) > 100)
  ) {
    throw new AppError("Face descriptor is invalid. Please capture the face again.", 400);
  }
  if (expectedLength && descriptor.length !== expectedLength) {
    throw new AppError("Face samples were generated by incompatible models. Please restart enrollment.", 400);
  }
}

function averageDescriptor(descriptors: number[][]) {
  return descriptors[0].map((_, index) =>
    descriptors.reduce((sum, descriptor) => sum + descriptor[index], 0) / descriptors.length,
  );
}

// Mirrors Human FaceRes' documented default descriptor similarity calculation.
export function faceDescriptorSimilarity(left: number[], right: number[]) {
  if (left.length !== right.length || left.length === 0) return 0;
  const squaredDistance = left.reduce((sum, value, index) => sum + (value - right[index]) ** 2, 0);
  if (squaredDistance === 0) return 1;
  const distance = Math.round(100 * 25 * squaredDistance) / 100;
  const normalized = (1 - Math.sqrt(distance) / 100 - 0.2) / 0.6;
  return Math.round(100 * Math.max(0, Math.min(1, normalized))) / 100;
}

class HumanFaceResProvider implements FaceRecognitionProvider {
  readonly name = "human-faceres-1to1";
  readonly modelVersion = "human-3.3.6-faceres-v1";

  async enroll(samples: FaceDescriptorSample[]): Promise<FaceEnrollmentTemplate> {
    if (samples.length !== 5) throw new AppError("Exactly 5 validated face samples are required.", 400);
    const descriptorLength = samples[0]?.embedding.length;
    for (const sample of samples) assertDescriptor(sample.embedding, descriptorLength);

    const descriptor = averageDescriptor(samples.map((sample) => sample.embedding));
    const minimumSimilarity = Math.min(
      ...samples.map((sample) => faceDescriptorSimilarity(sample.embedding, descriptor)),
    );
    if (minimumSimilarity < ENROLLMENT_CONSISTENCY_THRESHOLD) {
      throw new AppError("Face samples are not consistent enough. Capture the same person again in steady lighting.", 400);
    }

    const template: HumanFaceResTemplate = {
      provider: this.name,
      templateVersion: this.modelVersion,
      descriptor,
      descriptorLength,
      createdAt: new Date().toISOString(),
    };
    return {
      provider: this.name,
      templateVersion: this.modelVersion,
      template: JSON.stringify(template),
      qualityChecks: samples.map((sample) => sample.quality),
    };
  }

  async verify(embedding: number[], encryptedTemplate: string): Promise<FaceVerificationResult> {
    const template = JSON.parse(decryptBiometricTemplate(encryptedTemplate)) as HumanFaceResTemplate;
    if (template.provider !== this.name || template.templateVersion !== this.modelVersion) {
      throw new AppError("Face enrollment uses an unsupported model. Re-enrollment is required.", 428);
    }
    assertDescriptor(embedding, template.descriptorLength);
    assertDescriptor(template.descriptor, template.descriptorLength);
    const similarity = faceDescriptorSimilarity(embedding, template.descriptor);
    return { matched: similarity >= MATCH_THRESHOLD, similarity, modelVersion: this.modelVersion };
  }
}

export const faceRecognitionProvider: FaceRecognitionProvider = new HumanFaceResProvider();
