import { motion } from "framer-motion";
import {
  ArrowLeft,
  BarChart3,
  BrainCircuit,
  CheckCircle2,
  CircleDollarSign,
  Clock3,
  LineChart as LineChartIcon,
  RefreshCcw,
  Send,
  Sparkles,
  Target,
} from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import {
  Area,
  AreaChart,
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Line,
  LineChart,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { ThemeToggle } from "@/components/layout/ThemeToggle";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { SkeletonCard } from "@/components/ui/skeleton";
import { useToast } from "@/components/ui/toast-context";
import { getStoredAuthSession } from "@/features/auth/auth-service";
import { cn } from "@/lib/utils";
import { askBusinessIntelligence } from "./business-intelligence.api";
import { buildBusinessSnapshot } from "./business-intelligence.snapshot";
import type {
  BIChart,
  BIInsightSeverity,
  BIQueryResponse,
} from "./business-intelligence.types";

const quickQuestions = [
  "Show this month's revenue.",
  "Which projects are delayed?",
  "Who has pending approvals?",
  "Create a weekly business summary.",
  "Show customer pipeline insights.",
  "What deadlines are coming up?",
];

const chartColors: Record<string, string> = {
  primary: "hsl(var(--primary))",
  success: "rgb(16 185 129)",
  warning: "rgb(245 158 11)",
  danger: "rgb(244 63 94)",
  info: "rgb(14 165 233)",
};

const severityStyles: Record<BIInsightSeverity, string> = {
  danger: "border-rose-500/30 bg-rose-500/10 text-rose-700 dark:text-rose-200",
  info: "border-sky-500/30 bg-sky-500/10 text-sky-700 dark:text-sky-200",
  success: "border-emerald-500/30 bg-emerald-500/10 text-emerald-700 dark:text-emerald-200",
  warning: "border-amber-500/30 bg-amber-500/10 text-amber-700 dark:text-amber-200",
};

type TooltipPayload = {
  name?: string;
  value?: number | string;
  color?: string;
};

function CustomTooltip({
  active,
  label,
  payload,
}: {
  active?: boolean;
  label?: string;
  payload?: TooltipPayload[];
}) {
  if (!active || !payload?.length) return null;

  return (
    <div className="rounded-lg border bg-background/95 p-3 text-sm shadow-glass backdrop-blur-xl">
      <p className="mb-2 font-semibold">{label}</p>
      <div className="space-y-1">
        {payload.map((item) => (
          <div className="flex items-center justify-between gap-4" key={`${item.name}-${item.value}`}>
            <span className="text-muted-foreground">{item.name}</span>
            <span className="font-semibold">{String(item.value)}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function chartColor(color: string | undefined, index = 0) {
  const fallback = ["primary", "success", "warning", "danger", "info"][index % 5];
  return chartColors[color ?? fallback] ?? chartColors[fallback];
}

function BIChartCard({ chart }: { chart: BIChart }) {
  const primarySeries = chart.series[0];

  return (
    <Card className="glass h-full">
      <CardHeader>
        <div className="flex items-start justify-between gap-4">
          <div>
            <CardTitle>{chart.title}</CardTitle>
            <p className="mt-2 text-sm text-muted-foreground">
              Generated by Business Intelligence AI
            </p>
          </div>
          <span className="flex h-10 w-10 items-center justify-center rounded-md bg-primary/10 text-primary">
            <BarChart3 className="h-5 w-5" />
          </span>
        </div>
      </CardHeader>
      <CardContent>
        <div className="h-72">
          <ResponsiveContainer height="100%" width="100%">
            {chart.type === "bar" ? (
              <BarChart data={chart.data}>
                <CartesianGrid stroke="hsl(var(--border))" strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey={chart.x_key} stroke="hsl(var(--muted-foreground))" tickLine={false} />
                <YAxis stroke="hsl(var(--muted-foreground))" tickLine={false} width={54} />
                <Tooltip content={<CustomTooltip />} />
                {chart.series.map((series, index) => (
                  <Bar
                    dataKey={series.data_key}
                    fill={chartColor(series.color, index)}
                    key={series.data_key}
                    name={series.name}
                    radius={[6, 6, 0, 0]}
                  />
                ))}
              </BarChart>
            ) : chart.type === "pie" ? (
              <PieChart>
                <Tooltip content={<CustomTooltip />} />
                <Pie
                  cx="50%"
                  cy="50%"
                  data={chart.data}
                  dataKey={primarySeries?.data_key ?? "value"}
                  innerRadius={56}
                  nameKey={chart.x_key}
                  outerRadius={96}
                  paddingAngle={3}
                >
                  {chart.data.map((entry, index) => (
                    <Cell fill={chartColor(undefined, index)} key={`${entry[chart.x_key]}-${index}`} />
                  ))}
                </Pie>
              </PieChart>
            ) : chart.type === "line" ? (
              <LineChart data={chart.data}>
                <CartesianGrid stroke="hsl(var(--border))" strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey={chart.x_key} stroke="hsl(var(--muted-foreground))" tickLine={false} />
                <YAxis stroke="hsl(var(--muted-foreground))" tickLine={false} width={64} />
                <Tooltip content={<CustomTooltip />} />
                {chart.series.map((series, index) => (
                  <Line
                    dataKey={series.data_key}
                    dot={false}
                    key={series.data_key}
                    name={series.name}
                    stroke={chartColor(series.color, index)}
                    strokeWidth={3}
                    type="monotone"
                  />
                ))}
              </LineChart>
            ) : (
              <AreaChart data={chart.data}>
                <CartesianGrid stroke="hsl(var(--border))" strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey={chart.x_key} stroke="hsl(var(--muted-foreground))" tickLine={false} />
                <YAxis stroke="hsl(var(--muted-foreground))" tickLine={false} width={64} />
                <Tooltip content={<CustomTooltip />} />
                {chart.series.map((series, index) => (
                  <Area
                    dataKey={series.data_key}
                    fill={chartColor(series.color, index)}
                    fillOpacity={0.12}
                    key={series.data_key}
                    name={series.name}
                    stroke={chartColor(series.color, index)}
                    strokeWidth={3}
                    type="monotone"
                  />
                ))}
              </AreaChart>
            )}
          </ResponsiveContainer>
        </div>
      </CardContent>
    </Card>
  );
}

export function BusinessIntelligencePage() {
  const session = useMemo(() => getStoredAuthSession(), []);
  const snapshot = useMemo(() => buildBusinessSnapshot(), []);
  const token = session?.accessToken;
  const { toast } = useToast();
  const [question, setQuestion] = useState("Create a weekly business summary.");
  const [result, setResult] = useState<BIQueryResponse | null>(null);
  const [loading, setLoading] = useState(false);

  const runQuery = useCallback(
    async (nextQuestion: string) => {
      if (!token || !nextQuestion.trim()) return;
      setLoading(true);
      setQuestion(nextQuestion);
      try {
        const response = await askBusinessIntelligence(nextQuestion, snapshot, token);
        setResult(response);
        toast({
          title: "Business intelligence ready",
          description: "AI generated metrics, insights, and charts from connected modules.",
          type: "success",
        });
      } catch (error) {
        toast({
          title: "BI AI unavailable",
          description: error instanceof Error ? error.message : "AI service could not respond.",
          type: "error",
        });
      } finally {
        setLoading(false);
      }
    },
    [snapshot, toast, token],
  );

  useEffect(() => {
    if (token) {
      void runQuery("Create a weekly business summary.");
    }
  }, [runQuery, token]);

  if (!token) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-enterprise p-4">
        <EmptyState
          action={{ label: "Login", onClick: () => window.location.assign("/login") }}
          description="Business Intelligence AI needs a signed-in AI BOS user."
          icon={BrainCircuit}
          title="Authentication required"
        />
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-enterprise">
      <header className="sticky top-0 z-40 border-b bg-background/78 backdrop-blur-xl">
        <div className="container flex min-h-16 flex-wrap items-center justify-between gap-3 py-3">
          <div className="flex items-center gap-3">
            <Button asChild size="icon" type="button" variant="outline">
              <Link aria-label="Back to dashboard" to="/dashboard">
                <ArrowLeft className="h-4 w-4" />
              </Link>
            </Button>
            <div>
              <p className="text-sm font-semibold text-primary">AI / Business Intelligence</p>
              <h1 className="text-2xl font-bold">Business Intelligence AI</h1>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button disabled={loading} onClick={() => void runQuery(question)} type="button" variant="outline">
              <RefreshCcw className={cn("h-4 w-4", loading && "animate-spin")} />
              Refresh
            </Button>
            <ThemeToggle />
          </div>
        </div>
      </header>

      <div className="container space-y-6 py-6">
        <section className="grid gap-4 xl:grid-cols-[1.1fr_0.9fr]">
          <Card className="glass overflow-hidden">
            <CardContent className="p-6">
              <div className="mb-5 flex flex-wrap items-center gap-2">
                <span className="rounded-full border bg-background/70 px-3 py-1 text-xs font-bold text-primary">
                  Connected to business modules
                </span>
                <span className="rounded-full border bg-background/70 px-3 py-1 text-xs font-semibold text-muted-foreground">
                  Revenue, CRM, Projects, HR, Tasks, Meetings
                </span>
              </div>
              <div className="relative">
                <Sparkles className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-primary" />
                <textarea
                  className="min-h-32 w-full rounded-2xl border bg-background/75 px-10 py-3 text-sm outline-none transition focus:border-primary"
                  onChange={(event) => setQuestion(event.target.value)}
                  placeholder="Ask about revenue, projects, customers, employees, sales, tasks, or deadlines..."
                  value={question}
                />
              </div>
              <div className="mt-4 flex flex-wrap gap-2">
                <Button disabled={loading || !question.trim()} onClick={() => void runQuery(question)} type="button">
                  <Send className="h-4 w-4" />
                  Ask BI AI
                </Button>
                {quickQuestions.map((item) => (
                  <Button
                    disabled={loading}
                    key={item}
                    onClick={() => void runQuery(item)}
                    type="button"
                    variant="outline"
                  >
                    {item}
                  </Button>
                ))}
              </div>
            </CardContent>
          </Card>

          <Card className="glass">
            <CardHeader>
              <CardTitle>AI Response</CardTitle>
              <p className="text-sm text-muted-foreground">
                Answers are grounded in the connected module snapshot and backend context.
              </p>
            </CardHeader>
            <CardContent>
              {loading && !result ? (
                <div className="grid gap-3">
                  <SkeletonCard />
                </div>
              ) : result ? (
                <div className="whitespace-pre-wrap rounded-2xl border bg-background/65 p-4 text-sm leading-7">
                  {result.answer}
                </div>
              ) : (
                <EmptyState
                  description="Ask a business question to generate the first AI analysis."
                  icon={LineChartIcon}
                  title="No analysis yet"
                />
              )}
            </CardContent>
          </Card>
        </section>

        {loading && result ? (
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <SkeletonCard />
            <SkeletonCard />
            <SkeletonCard />
            <SkeletonCard />
          </div>
        ) : null}

        {result && (
          <>
            <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
              {result.metrics.map((metric, index) => (
                <motion.div
                  animate={{ opacity: 1, y: 0 }}
                  initial={{ opacity: 0, y: 14 }}
                  key={metric.label}
                  transition={{ delay: index * 0.04 }}
                >
                  <Card className="glass h-full">
                    <CardContent className="p-5">
                      <CircleDollarSign className="mb-4 h-5 w-5 text-primary" />
                      <p className="text-sm text-muted-foreground">{metric.label}</p>
                      <p className="mt-2 text-3xl font-bold">{metric.value}</p>
                      {metric.change && (
                        <p className="mt-3 text-sm font-semibold text-emerald-600 dark:text-emerald-300">
                          {metric.change}
                        </p>
                      )}
                      {metric.source && (
                        <p className="mt-3 text-xs font-semibold text-muted-foreground">
                          Source: {metric.source}
                        </p>
                      )}
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </section>

            <section className="grid gap-4 xl:grid-cols-2">
              {result.charts.map((chart) => (
                <BIChartCard chart={chart} key={chart.id} />
              ))}
            </section>

            <section className="grid gap-4 xl:grid-cols-[1fr_0.8fr_0.8fr]">
              <Card className="glass">
                <CardHeader>
                  <CardTitle>Insights</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {result.insights.map((insight) => (
                    <div
                      className={cn("rounded-2xl border p-4", severityStyles[insight.severity])}
                      key={insight.title}
                    >
                      <p className="font-semibold">{insight.title}</p>
                      <p className="mt-2 text-sm leading-6">{insight.detail}</p>
                    </div>
                  ))}
                </CardContent>
              </Card>

              <Card className="glass">
                <CardHeader>
                  <CardTitle>Recommended Actions</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {result.actions.map((action) => (
                    <div className="flex gap-3 rounded-2xl border bg-background/65 p-3" key={action}>
                      <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                      <p className="text-sm leading-6">{action}</p>
                    </div>
                  ))}
                </CardContent>
              </Card>

              <Card className="glass">
                <CardHeader>
                  <CardTitle>Sources</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {result.sources.map((source) => (
                    <div className="rounded-2xl border bg-background/65 p-4" key={source.module}>
                      <div className="flex items-center justify-between gap-3">
                        <div>
                          <p className="font-semibold">{source.module}</p>
                          <p className="mt-1 text-xs text-muted-foreground">{source.label}</p>
                        </div>
                        <span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold text-primary">
                          {source.record_count}
                        </span>
                      </div>
                    </div>
                  ))}
                  <div className="flex items-center gap-2 rounded-2xl border bg-background/65 p-4 text-xs text-muted-foreground">
                    <Clock3 className="h-4 w-4" />
                    Generated {new Date(result.generated_at).toLocaleString()}
                  </div>
                </CardContent>
              </Card>
            </section>

            <Card className="glass">
              <CardContent className="flex flex-col gap-4 p-5 md:flex-row md:items-center md:justify-between">
                <div>
                  <p className="font-semibold">Business Intelligence Intent</p>
                  <p className="mt-1 text-sm text-muted-foreground">
                    {result.intent.replace(/_/g, " ")}
                  </p>
                </div>
                <div className="flex items-center gap-2 text-sm font-semibold text-primary">
                  <Target className="h-4 w-4" />
                  Chart-backed answer
                </div>
              </CardContent>
            </Card>
          </>
        )}
      </div>
    </main>
  );
}
