import type { Product } from "./products.types";

export const productCategories = ["Software", "Hardware", "Services", "Subscriptions", "Add-ons", "Training"];
export const suppliers = ["AI BOS Labs", "CloudStack", "OpsWare", "DataGrid", "SecureDesk"];

export const seedProducts: Product[] = [
 {
 id: "prod-1",
 productName: "AI BOS Enterprise License",
 sku: "SKU-AIBOS-ENT",
 category: "Subscriptions",
 price: 1499,
 costPrice: 420,
 stock: 128,
 supplier: "AI BOS Labs",
 barcode: "8901001202601",
 images: ["AIB"],
 updatedAt: "2026-07-18",
 },
 {
 id: "prod-2",
 productName: "CRM Automation Add-on",
 sku: "SKU-CRM-AUTO",
 category: "Add-ons",
 price: 399,
 costPrice: 95,
 stock: 42,
 supplier: "AI BOS Labs",
 barcode: "8901001202602",
 images: ["CRM"],
 updatedAt: "2026-07-17",
 },
 {
 id: "prod-3",
 productName: "Secure Meeting Room Kit",
 sku: "SKU-HW-MTG",
 category: "Hardware",
 price: 899,
 costPrice: 610,
 stock: 7,
 supplier: "SecureDesk",
 barcode: "8901001202603",
 images: ["SMR"],
 updatedAt: "2026-07-16",
 },
 {
 id: "prod-4",
 productName: "Analytics Data Connector",
 sku: "SKU-DATA-CON",
 category: "Software",
 price: 249,
 costPrice: 70,
 stock: 0,
 supplier: "DataGrid",
 barcode: "8901001202604",
 images: ["ADC"],
 updatedAt: "2026-07-15",
 },
 {
 id: "prod-5",
 productName: "Admin Training Workshop",
 sku: "SKU-TRN-ADM",
 category: "Training",
 price: 1200,
 costPrice: 380,
 stock: 16,
 supplier: "OpsWare",
 barcode: "8901001202605",
 images: ["ATW"],
 updatedAt: "2026-07-14",
 },
];
