export const voiceCommands = [
  "open_dashboard",
  "open_crm",
  "open_projects",
  "open_tasks",
  "open_employees",
  "open_finance",
  "open_analytics",
  "open_documents",
  "open_settings",
  "open_admin",
  "open_workflows",
  "create_task",
  "create_project",
  "generate_invoice",
  "search_employees",
  "start_ai_chat",
] as const;

export type VoiceCommand = (typeof voiceCommands)[number];

export const voiceCommandMappings: Record<VoiceCommand, { action: string; params?: Record<string, string>; route?: string }> = {
  open_dashboard: { action: "navigate", route: "/dashboard" },
  open_crm: { action: "navigate", route: "/crm" },
  open_projects: { action: "navigate", route: "/projects" },
  open_tasks: { action: "navigate", route: "/tasks" },
  open_employees: { action: "navigate", route: "/employees" },
  open_finance: { action: "navigate", route: "/finance" },
  open_analytics: { action: "navigate", route: "/analytics" },
  open_documents: { action: "navigate", route: "/documents" },
  open_settings: { action: "navigate", route: "/settings" },
  open_admin: { action: "navigate", route: "/admin" },
  open_workflows: { action: "navigate", route: "/workflows" },
  create_task: { action: "quick_create", params: { type: "task" } },
  create_project: { action: "quick_create", params: { type: "project" } },
  generate_invoice: { action: "quick_create", params: { type: "invoice" } },
  search_employees: { action: "navigate", route: "/employees" },
  start_ai_chat: { action: "open_ai_assistant" },
};

export const voiceTriggers: Record<string, VoiceCommand> = {
  "open dashboard": "open_dashboard",
  "go to dashboard": "open_dashboard",
  "show dashboard": "open_dashboard",
  "open crm": "open_crm",
  "go to crm": "open_crm",
  "show crm": "open_crm",
  "open projects": "open_projects",
  "go to projects": "open_projects",
  "show projects": "open_projects",
  "open tasks": "open_tasks",
  "go to tasks": "open_tasks",
  "show tasks": "open_tasks",
  "open employees": "open_employees",
  "go to employees": "open_employees",
  "show employees": "open_employees",
  "open finance": "open_finance",
  "go to finance": "open_finance",
  "show finance": "open_finance",
  "open analytics": "open_analytics",
  "go to analytics": "open_analytics",
  "show analytics": "open_analytics",
  "open documents": "open_documents",
  "go to documents": "open_documents",
  "show documents": "open_documents",
  "open settings": "open_settings",
  "go to settings": "open_settings",
  "create task": "create_task",
  "new task": "create_task",
  "add task": "create_task",
  "create project": "create_project",
  "new project": "create_project",
  "add project": "create_project",
  "generate invoice": "generate_invoice",
  "new invoice": "generate_invoice",
  "create invoice": "generate_invoice",
  "search employees": "search_employees",
  "find employee": "search_employees",
  "start ai chat": "start_ai_chat",
  "open ai assistant": "start_ai_chat",
  "ai assistant": "start_ai_chat",
};

export const voiceStatuses = ["idle", "listening", "processing", "speaking", "error"] as const;
export type VoiceStatus = (typeof voiceStatuses)[number];