import type { Workflow, WorkflowExecutionLog } from "./workflows.types";

export const workflowStatuses = ["Active", "Paused", "Draft", "Archived"] as const;
export const workflowStepTypes = ["trigger", "action", "condition", "delay", "approval", "notification"] as const;
export const workflowTriggerTypes = ["customer_created", "manual", "schedule", "webhook", "project_created", "invoice_created"] as const;
export const workflowActionTypes = ["create_crm_lead", "assign_sales_executive", "schedule_meeting", "send_email", "create_task", "update_record", "send_notification", "create_project"] as const;
export const workflowConditionOperators = ["equals", "not_equals", "contains", "greater_than", "less_than", "is_empty", "is_not_empty"] as const;

function createId(prefix = "step") {
  return `${prefix}-${crypto.randomUUID().slice(0, 8)}`;
}

export const seedWorkflows: Workflow[] = [
  {
    id: "wf-1",
    name: "Customer Onboarding Automation",
    description: "Automated workflow triggered when a new customer is created. Creates CRM lead, assigns sales executive, schedules meeting, sends welcome email, and creates follow-up task.",
    status: "Active",
    isTemplate: false,
    triggerType: "customer_created",
    triggerConfig: { entity: "customer", event: "created" },
    steps: [
      {
        stepId: createId("step"),
        type: "trigger",
        name: "Customer Created",
        triggerType: "customer_created",
        config: { entity: "customer", event: "created" },
        order: 0,
      },
      {
        stepId: createId("step"),
        type: "action",
        name: "Create CRM Lead",
        actionType: "create_crm_lead",
        config: { source: "customer_created", autoAssign: true },
        nextStepId: "next-2",
        order: 1,
      },
      {
        stepId: createId("step"),
        type: "action",
        name: "Assign Sales Executive",
        actionType: "assign_sales_executive",
        config: { method: "round_robin", department: "Sales" },
        nextStepId: "next-3",
        order: 2,
      },
      {
        stepId: createId("step"),
        type: "action",
        name: "Schedule Meeting",
        actionType: "schedule_meeting",
        config: { duration: 30, calendar: "Google", attendees: ["sales_executive", "customer"] },
        nextStepId: "next-4",
        order: 3,
      },
      {
        stepId: createId("step"),
        type: "action",
        name: "Send Welcome Email",
        actionType: "send_email",
        config: { template: "welcome_customer", channel: "email" },
        nextStepId: "next-5",
        order: 4,
      },
      {
        stepId: createId("step"),
        type: "action",
        name: "Create Follow-up Task",
        actionType: "create_task",
        config: { title: "Follow up with new customer", priority: "Medium", dueDays: 7, assignee: "sales_executive" },
        order: 5,
      },
    ],
    tags: ["crm", "onboarding", "sales", "automation"],
    executionCount: 142,
    lastExecutedAt: "2026-07-20T10:30:00Z",
    createdBy: "Administrator",
    updatedBy: "Administrator",
    createdAt: "2026-06-15",
    updatedAt: "2026-07-18",
    executionHistory: [
      {
        executionId: `exec-${Date.now()}-1`,
        startedAt: "2026-07-20T10:30:00Z",
        finishedAt: "2026-07-20T10:30:45Z",
        status: "completed",
        triggeredBy: "system",
        inputPayload: { customerId: "cust-123", customerName: "Orbit Finance" },
        outputPayload: { leadId: "lead-456", taskId: "task-789" },
        stepLogs: [
          { stepId: "trigger-1", startedAt: "2026-07-20T10:30:00Z", finishedAt: "2026-07-20T10:30:01Z", status: "completed" },
          { stepId: "step-1", startedAt: "2026-07-20T10:30:01Z", finishedAt: "2026-07-20T10:30:15Z", status: "completed" },
          { stepId: "step-2", startedAt: "2026-07-20T10:30:15Z", finishedAt: "2026-07-20T10:30:20Z", status: "completed" },
          { stepId: "step-3", startedAt: "2026-07-20T10:30:20Z", finishedAt: "2026-07-20T10:30:30Z", status: "completed" },
          { stepId: "step-4", startedAt: "2026-07-20T10:30:30Z", finishedAt: "2026-07-20T10:30:40Z", status: "completed" },
          { stepId: "step-5", startedAt: "2026-07-20T10:30:40Z", finishedAt: "2026-07-20T10:30:45Z", status: "completed" },
        ],
      } as WorkflowExecutionLog,
      {
        executionId: `exec-${Date.now()}-2`,
        startedAt: "2026-07-19T14:15:00Z",
        finishedAt: "2026-07-19T14:15:42Z",
        status: "completed",
        triggeredBy: "system",
        inputPayload: { customerId: "cust-124", customerName: "Zenith Health" },
        outputPayload: { leadId: "lead-457", taskId: "task-790" },
        stepLogs: [
          { stepId: "trigger-1", startedAt: "2026-07-19T14:15:00Z", finishedAt: "2026-07-19T14:15:02Z", status: "completed" },
          { stepId: "step-1", startedAt: "2026-07-19T14:15:02Z", finishedAt: "2026-07-19T14:15:18Z", status: "completed" },
          { stepId: "step-2", startedAt: "2026-07-19T14:15:18Z", finishedAt: "2026-07-19T14:15:25Z", status: "completed" },
          { stepId: "step-3", startedAt: "2026-07-19T14:15:25Z", finishedAt: "2026-07-19T14:15:35Z", status: "completed" },
          { stepId: "step-4", startedAt: "2026-07-19T14:15:35Z", finishedAt: "2026-07-19T14:15:40Z", status: "completed" },
          { stepId: "step-5", startedAt: "2026-07-19T14:15:40Z", finishedAt: "2026-07-19T14:15:42Z", status: "completed" },
        ],
      } as WorkflowExecutionLog,
    ],
  },
  {
    id: "wf-2",
    name: "Invoice Approval Workflow",
    description: "Multi-level approval workflow for invoices above $10,000. Routes to Finance Manager and then CEO for final approval.",
    status: "Paused",
    isTemplate: false,
    triggerType: "invoice_created",
    triggerConfig: { entity: "invoice", event: "created", condition: "amount > 10000" },
    steps: [
      {
        stepId: createId("step"),
        type: "trigger",
        name: "Invoice Created",
        triggerType: "invoice_created",
        config: { entity: "invoice", event: "created", condition: "amount > 10000" },
        order: 0,
      },
      {
        stepId: createId("step"),
        type: "approval",
        name: "Finance Manager Approval",
        config: { approver: "Finance Manager", timeoutHours: 24 },
        nextStepId: "next-2",
        approverRoles: ["Manager"],
        order: 1,
      },
      {
        stepId: createId("step"),
        type: "approval",
        name: "CEO Final Approval",
        config: { approver: "Owner", timeoutHours: 48 },
        nextStepId: "next-3",
        approverRoles: ["Owner"],
        order: 2,
      },
      {
        stepId: createId("step"),
        type: "notification",
        name: "Notify Accounts Payable",
        actionType: "send_notification",
        config: { channel: "email", template: "invoice_approved" },
        notificationChannels: ["email"],
        order: 3,
      },
    ],
    tags: ["finance", "invoice", "approval"],
    executionCount: 89,
    lastExecutedAt: "2026-07-19T16:45:00Z",
    createdBy: "Administrator",
    updatedBy: "Manager",
    createdAt: "2026-05-20",
    updatedAt: "2026-07-15",
  },
  {
    id: "wf-3",
    name: "Employee Onboarding",
    description: "Standard onboarding workflow for new employees. Creates tasks, assigns equipment, schedules training, and sends welcome notifications.",
    status: "Active",
    isTemplate: true,
    triggerType: "manual",
    triggerConfig: {},
    steps: [
      {
        stepId: createId("step"),
        type: "trigger",
        name: "Manual Trigger",
        triggerType: "manual",
        config: { triggeredBy: "HR" },
        order: 0,
      },
      {
        stepId: createId("step"),
        type: "action",
        name: "Create Employee Profile",
        actionType: "create_task",
        config: { department: "HR", priority: "High" },
        nextStepId: "next-2",
        order: 1,
      },
      {
        stepId: createId("step"),
        type: "action",
        name: "Assign Equipment",
        actionType: "update_record",
        config: { entity: "employee", field: "equipment_assigned" },
        nextStepId: "next-3",
        order: 2,
      },
      {
        stepId: createId("step"),
        type: "delay",
        name: "Wait 1 Day",
        config: { reason: "Allow profile setup" },
        delayMinutes: 1440,
        nextStepId: "next-4",
        order: 3,
      },
      {
        stepId: createId("step"),
        type: "action",
        name: "Schedule Training",
        actionType: "schedule_meeting",
        config: { type: "training", duration: 60 },
        nextStepId: "next-5",
        order: 4,
      },
      {
        stepId: createId("step"),
        type: "notification",
        name: "Send Welcome Notification",
        actionType: "send_notification",
        config: { channel: "email", template: "welcome_employee" },
        notificationChannels: ["email", "slack"],
        order: 5,
      },
    ],
    tags: ["hr", "onboarding", "employee"],
    executionCount: 34,
    lastExecutedAt: "2026-07-18T09:00:00Z",
    createdBy: "Ananya Iyer",
    updatedBy: "Ananya Iyer",
    createdAt: "2026-04-10",
    updatedAt: "2026-07-10",
  },
  {
    id: "wf-4",
    name: "Lead Scoring Automation",
    description: "Evaluates new CRM leads based on company size, industry, and engagement score. High-value leads are prioritized for immediate follow-up.",
    status: "Draft",
    isTemplate: false,
    triggerType: "webhook",
    triggerConfig: { endpoint: "/webhooks/crm/lead-created", method: "POST" },
    steps: [
      {
        stepId: createId("step"),
        type: "trigger",
        name: "Webhook: Lead Created",
        triggerType: "webhook",
        config: { endpoint: "/webhooks/crm/lead-created" },
        order: 0,
      },
      {
        stepId: createId("step"),
        type: "condition",
        name: "Check Lead Value",
        config: { field: "estimated_value", operator: "greater_than", value: "50000" },
        branches: [
          { condition: "High Value", operator: "greater_than", value: "50000", nextStepId: "high-value" },
          { condition: "Standard", operator: "equals", value: "standard", nextStepId: "standard" },
        ],
        order: 1,
      },
      {
        stepId: "high-value",
        type: "action",
        name: "Escalate to Senior Sales",
        actionType: "assign_sales_executive",
        config: { method: "senior_first", priority: "High" },
        nextStepId: "notify-high",
        order: 2,
      },
      {
        stepId: "notify-high",
        type: "notification",
        name: "Alert Sales Director",
        actionType: "send_notification",
        config: { channel: "email", template: "high_value_lead_alert" },
        notificationChannels: ["email"],
        order: 3,
      },
      {
        stepId: "standard",
        type: "action",
        name: "Assign to Sales Rep",
        actionType: "assign_sales_executive",
        config: { method: "round_robin", priority: "Medium" },
        nextStepId: "notify-standard",
        order: 2,
      },
      {
        stepId: "notify-standard",
        type: "notification",
        name: "Notify Assigned Rep",
        actionType: "send_notification",
        config: { channel: "email", template: "new_lead_assigned" },
        notificationChannels: ["email"],
        order: 3,
      },
    ],
    tags: ["crm", "sales", "lead-scoring"],
    executionCount: 0,
    createdBy: "Sales Manager",
    updatedBy: "Sales Manager",
    createdAt: "2026-07-12",
    updatedAt: "2026-07-12",
  },
  {
    id: "wf-5",
    name: "Weekly Report Generation",
    description: "Generates and distributes weekly business reports to stakeholders every Monday at 8 AM.",
    status: "Active",
    isTemplate: true,
    triggerType: "schedule",
    triggerConfig: { cron: "0 8 * * 1", timezone: "Asia/Kolkata" },
    steps: [
      {
        stepId: createId("step"),
        type: "trigger",
        name: "Schedule: Every Monday 8 AM",
        triggerType: "schedule",
        config: { cron: "0 8 * * 1", timezone: "Asia/Kolkata" },
        order: 0,
      },
      {
        stepId: createId("step"),
        type: "action",
        name: "Generate Weekly Report",
        actionType: "update_record",
        config: { reportType: "weekly_summary", modules: ["projects", "finance", "crm", "tasks"] },
        nextStepId: "next-2",
        order: 1,
      },
      {
        stepId: createId("step"),
        type: "action",
        name: "Send Report to Stakeholders",
        actionType: "send_email",
        config: { template: "weekly_report", recipients: ["admin", "ceo", "managers"] },
        notificationChannels: ["email"],
        order: 2,
      },
    ],
    tags: ["reports", "automation", "schedule"],
    executionCount: 12,
    lastExecutedAt: "2026-07-14T08:00:00Z",
    createdBy: "Administrator",
    updatedBy: "Administrator",
    createdAt: "2026-05-01",
    updatedAt: "2026-07-14",
  },
];
