import type { AttendanceRecord, Department, Designation, Employee, Holiday, LeaveRequest } from "./employees.types";

export const departments: Department[] = [
  { name: "Operations", lead: "Priya Sharma", employees: 3, budget: 820000 },
  { name: "Engineering", lead: "Sneha Joshi", employees: 1, budget: 1200000 },
  { name: "Human Resources", lead: "Ananya Iyer", employees: 1, budget: 410000 },
  { name: "Finance", lead: "Vikram Nair", employees: 1, budget: 640000 },
  { name: "Sales", lead: "Neha Reddy", employees: 1, budget: 560000 },
  { name: "Customer Success", lead: "Karan Malhotra", employees: 1, budget: 380000 },
  { name: "Executive", lead: "Rajeev Khanna", employees: 1, budget: 0 },
];

export const designations: Designation[] = [
  { title: "Associate", department: "Operations", level: "L2", employees: 1 },
  { title: "Product Manager", department: "Operations", level: "L5", employees: 1 },
  { title: "Platform Administrator", department: "Operations", level: "L5", employees: 1 },
  { title: "Senior Software Engineer", department: "Engineering", level: "L4", employees: 1 },
  { title: "HR Business Partner", department: "Human Resources", level: "L3", employees: 1 },
  { title: "Finance Analyst", department: "Finance", level: "L3", employees: 1 },
  { title: "Sales Executive", department: "Sales", level: "L3", employees: 1 },
  { title: "Customer Support Lead", department: "Customer Success", level: "L3", employees: 1 },
  { title: "Chief Executive Officer", department: "Executive", level: "L7", employees: 1 },
  { title: "Guest Consultant", department: "Executive", level: "L1", employees: 1 },
];

export const holidays: Holiday[] = [
  { name: "Independence Day", date: "2026-08-15", type: "National" },
  { name: "Founders Day", date: "2026-09-12", type: "Company" },
  { name: "Diwali", date: "2026-11-08", type: "Festival" },
  { name: "Year End Break", date: "2026-12-25", type: "Company" },
];

export const seedEmployees: Employee[] = [
  {
    id: "emp-1",
    employeeCode: "EMP-2026-001",
    name: "Rajeev Khanna",
    avatar: "RK",
    email: "rajeev.khanna@aibos.company",
    phone: "+91 98450 11001",
    location: "Bengaluru, India",
    department: "Executive",
    designation: "Chief Executive Officer",
    employmentType: "Full Time",
    joiningDate: "2024-01-08",
    status: "Active",
    personalInformation: { dateOfBirth: "1980-03-14", gender: "Male", nationality: "Indian", maritalStatus: "Married" },
    contact: { address: "MG Road, Bengaluru", emergencyContact: "+91 98450 11091" },
    skills: ["Strategy", "Leadership", "Business Intelligence", "AI Governance"],
    experience: ["Owner and CEO at AI BOS", "VP Operations at NimbusWorks"],
    education: ["MBA, IIM Bengaluru", "B.Tech, Computer Science"],
    documents: [
      { name: "identity-proof.pdf", type: "Identity", size: "780 KB" },
      { name: "offer-letter.pdf", type: "HR", size: "310 KB" },
    ],
    salaryDetails: { annualCtc: 8500000, monthlySalary: 708333, bank: "HDFC Bank", taxId: "AKPRK9021Q" },
    performanceScore: 96,
  },
  {
    id: "emp-2",
    employeeCode: "EMP-2026-002",
    name: "Priya Sharma",
    avatar: "PS",
    email: "priya.sharma@aibos.company",
    phone: "+91 98450 11002",
    location: "Bengaluru, India",
    department: "Operations",
    designation: "Platform Administrator",
    employmentType: "Full Time",
    joiningDate: "2024-02-19",
    status: "Active",
    personalInformation: { dateOfBirth: "1990-07-02", gender: "Female", nationality: "Indian", maritalStatus: "Single" },
    contact: { address: "Indiranagar, Bengaluru", emergencyContact: "+91 98450 11092" },
    skills: ["RBAC", "Security", "Systems Administration", "Integrations"],
    experience: ["Platform Administrator at AI BOS", "IT Systems Lead at CloudNine"],
    education: ["B.E, Information Science"],
    documents: [{ name: "admin-contract.pdf", type: "Contract", size: "540 KB" }],
    salaryDetails: { annualCtc: 3200000, monthlySalary: 266666, bank: "ICICI Bank", taxId: "BFPPS4456R" },
    performanceScore: 93,
  },
  {
    id: "emp-3",
    employeeCode: "EMP-2026-003",
    name: "Rohan Kapoor",
    avatar: "RK",
    email: "rohan.kapoor@aibos.company",
    phone: "+91 98450 11003",
    location: "Bengaluru, India",
    department: "Operations",
    designation: "Product Manager",
    employmentType: "Full Time",
    joiningDate: "2024-03-11",
    status: "Active",
    personalInformation: { dateOfBirth: "1992-11-27", gender: "Male", nationality: "Indian", maritalStatus: "Married" },
    contact: { address: "Koramangala, Bengaluru", emergencyContact: "+91 98450 11093" },
    skills: ["Product Strategy", "Delivery Management", "Workflow Automation"],
    experience: ["Product Manager at AI BOS", "Business Analyst at SaaSWorks"],
    education: ["MBA, Business Operations", "B.Tech, Computer Science"],
    documents: [{ name: "offer-letter.pdf", type: "HR", size: "340 KB" }],
    salaryDetails: { annualCtc: 2800000, monthlySalary: 233333, bank: "Axis Bank", taxId: "CKQPR7788T" },
    performanceScore: 91,
  },
  {
    id: "emp-4",
    employeeCode: "EMP-2026-004",
    name: "Ananya Iyer",
    avatar: "AI",
    email: "ananya.iyer@aibos.company",
    phone: "+91 98450 11004",
    location: "Bengaluru, India",
    department: "Human Resources",
    designation: "HR Business Partner",
    employmentType: "Full Time",
    joiningDate: "2024-04-22",
    status: "Active",
    personalInformation: { dateOfBirth: "1993-05-30", gender: "Female", nationality: "Indian", maritalStatus: "Single" },
    contact: { address: "HSR Layout, Bengaluru", emergencyContact: "+91 98450 11094" },
    skills: ["Employee Records", "Onboarding", "Policy Management", "Payroll"],
    experience: ["HR Business Partner at AI BOS", "HR Generalist at PeopleFirst"],
    education: ["MBA, Human Resources"],
    documents: [{ name: "nda.pdf", type: "Legal", size: "260 KB" }],
    salaryDetails: { annualCtc: 2100000, monthlySalary: 175000, bank: "SBI", taxId: "DLZPA3321M" },
    performanceScore: 90,
  },
  {
    id: "emp-5",
    employeeCode: "EMP-2026-005",
    name: "Vikram Nair",
    avatar: "VN",
    email: "vikram.nair@aibos.company",
    phone: "+91 98450 11005",
    location: "Bengaluru, India",
    department: "Finance",
    designation: "Finance Analyst",
    employmentType: "Full Time",
    joiningDate: "2024-05-06",
    status: "Active",
    personalInformation: { dateOfBirth: "1991-01-22", gender: "Male", nationality: "Indian", maritalStatus: "Married" },
    contact: { address: "Whitefield, Bengaluru", emergencyContact: "+91 98450 11095" },
    skills: ["FP&A", "Compliance", "Budgeting", "Reporting"],
    experience: ["Finance Analyst at AI BOS", "Audit Associate at FinCore"],
    education: ["CA Intermediate", "B.Com Finance"],
    documents: [{ name: "tax-declaration.pdf", type: "Finance", size: "410 KB" }],
    salaryDetails: { annualCtc: 2400000, monthlySalary: 200000, bank: "ICICI Bank", taxId: "PQRSX6789Z" },
    performanceScore: 88,
  },
  {
    id: "emp-6",
    employeeCode: "EMP-2026-006",
    name: "Neha Reddy",
    avatar: "NR",
    email: "neha.reddy@aibos.company",
    phone: "+91 98450 11006",
    location: "Bengaluru, India",
    department: "Sales",
    designation: "Sales Executive",
    employmentType: "Full Time",
    joiningDate: "2024-06-14",
    status: "Active",
    personalInformation: { dateOfBirth: "1995-09-18", gender: "Female", nationality: "Indian", maritalStatus: "Single" },
    contact: { address: "Jayanagar, Bengaluru", emergencyContact: "+91 98450 11096" },
    skills: ["CRM", "Pipeline Management", "Negotiation", "Forecasting"],
    experience: ["Sales Executive at AI BOS", "Account Executive at LeadWave"],
    education: ["BBA, Marketing"],
    documents: [{ name: "offer-letter.pdf", type: "HR", size: "300 KB" }],
    salaryDetails: { annualCtc: 1800000, monthlySalary: 150000, bank: "HDFC Bank", taxId: "EMTPN2210K" },
    performanceScore: 87,
  },
  {
    id: "emp-7",
    employeeCode: "EMP-2026-007",
    name: "Karan Malhotra",
    avatar: "KM",
    email: "karan.malhotra@aibos.company",
    phone: "+91 98450 11007",
    location: "Bengaluru, India",
    department: "Customer Success",
    designation: "Customer Support Lead",
    employmentType: "Full Time",
    joiningDate: "2024-07-09",
    status: "On Leave",
    personalInformation: { dateOfBirth: "1994-12-03", gender: "Male", nationality: "Indian", maritalStatus: "Single" },
    contact: { address: "BTM Layout, Bengaluru", emergencyContact: "+91 98450 11097" },
    skills: ["Customer Support", "Troubleshooting", "User Directory", "Escalation Management"],
    experience: ["Customer Support Lead at AI BOS", "Support Engineer at Helptrail"],
    education: ["B.Sc, Computer Applications"],
    documents: [{ name: "identity-proof.pdf", type: "Identity", size: "690 KB" }],
    salaryDetails: { annualCtc: 1600000, monthlySalary: 133333, bank: "Kotak Mahindra", taxId: "FQNPK5567J" },
    performanceScore: 85,
  },
  {
    id: "emp-8",
    employeeCode: "EMP-2026-008",
    name: "Sneha Joshi",
    avatar: "SJ",
    email: "sneha.joshi@aibos.company",
    phone: "+91 98450 11008",
    location: "Bengaluru, India",
    department: "Engineering",
    designation: "Senior Software Engineer",
    employmentType: "Full Time",
    joiningDate: "2024-08-25",
    status: "Active",
    personalInformation: { dateOfBirth: "1993-02-11", gender: "Female", nationality: "Indian", maritalStatus: "Single" },
    contact: { address: "Marathahalli, Bengaluru", emergencyContact: "+91 98450 11098" },
    skills: ["Integrations", "AI Systems", "Automation", "Platform Reliability"],
    experience: ["Senior Software Engineer at AI BOS", "Backend Engineer at DataForge"],
    education: ["B.Tech, Computer Science"],
    documents: [{ name: "engineering-contract.pdf", type: "Contract", size: "1.0 MB" }],
    salaryDetails: { annualCtc: 3400000, monthlySalary: 283333, bank: "Axis Bank", taxId: "GRSPJ8890W" },
    performanceScore: 92,
  },
  {
    id: "emp-9",
    employeeCode: "EMP-2026-009",
    name: "Aditya Rao",
    avatar: "AR",
    email: "aditya.rao@aibos.company",
    phone: "+91 98450 11009",
    location: "Bengaluru, India",
    department: "Operations",
    designation: "Associate",
    employmentType: "Full Time",
    joiningDate: "2025-01-13",
    status: "Active",
    personalInformation: { dateOfBirth: "1998-06-25", gender: "Male", nationality: "Indian", maritalStatus: "Single" },
    contact: { address: "Electronic City, Bengaluru", emergencyContact: "+91 98450 11099" },
    skills: ["Task Execution", "Documentation", "Meetings", "AI Copilot"],
    experience: ["Associate at AI BOS"],
    education: ["B.Com, General"],
    documents: [{ name: "offer-letter.pdf", type: "HR", size: "290 KB" }],
    salaryDetails: { annualCtc: 900000, monthlySalary: 75000, bank: "SBI", taxId: "HTLPR1123D" },
    performanceScore: 84,
  },
  {
    id: "emp-10",
    employeeCode: "EMP-2026-010",
    name: "Meera Pillai",
    avatar: "MP",
    email: "meera.pillai@aibos.company",
    phone: "+91 98450 11010",
    location: "Bengaluru, India",
    department: "Executive",
    designation: "Guest Consultant",
    employmentType: "Contract",
    joiningDate: "2026-05-04",
    status: "Active",
    personalInformation: { dateOfBirth: "1989-10-16", gender: "Female", nationality: "Indian", maritalStatus: "Married" },
    contact: { address: "Domlur, Bengaluru", emergencyContact: "+91 98450 11100" },
    skills: ["Read-Only Access", "Advisory"],
    experience: ["External Consultant for AI BOS"],
    education: ["MA, Business Advisory"],
    documents: [{ name: "nda.pdf", type: "Legal", size: "220 KB" }],
    salaryDetails: { annualCtc: 0, monthlySalary: 0, bank: "Not applicable", taxId: "Not applicable" },
    performanceScore: 80,
  },
];

export const seedAttendance: AttendanceRecord[] = [
  { id: "att-1", employeeId: "emp-1", date: "2026-07-24", checkIn: "09:05", checkOut: "18:10", workingHours: 9.1, status: "Present" },
  { id: "att-2", employeeId: "emp-2", date: "2026-07-24", checkIn: "09:00", checkOut: "17:55", workingHours: 8.9, status: "Present" },
  { id: "att-3", employeeId: "emp-3", date: "2026-07-24", checkIn: "09:20", workingHours: 5.2, status: "Present" },
  { id: "att-7", employeeId: "emp-7", date: "2026-07-24", workingHours: 0, status: "On Leave" },
  { id: "att-9", employeeId: "emp-9", date: "2026-07-24", checkIn: "09:30", checkOut: "18:00", workingHours: 8.5, status: "Present" },
];

export const seedLeaveRequests: LeaveRequest[] = [
  { id: "leave-1", employeeId: "emp-7", type: "Sick Leave", from: "2026-07-24", to: "2026-07-26", reason: "Medical recovery", status: "Approved", approver: "Ananya Iyer" },
  { id: "leave-2", employeeId: "emp-6", type: "Paid Leave", from: "2026-08-05", to: "2026-08-08", reason: "Family travel", status: "Pending", approver: "Ananya Iyer" },
];
