import type { AttendanceRecord, Department, Designation, Employee, Holiday, LeaveRequest } from "./employees.types";

export const departments: Department[] = [
  { name: "Engineering", lead: "Sofia Alvarez", employees: 42, budget: 1200000 },
  { name: "Operations", lead: "Aman Verma", employees: 28, budget: 820000 },
  { name: "Human Resources", lead: "HR Lead", employees: 12, budget: 410000 },
  { name: "Finance", lead: "Arjun Mehta", employees: 18, budget: 640000 },
  { name: "Customer Success", lead: "Maya Chen", employees: 25, budget: 720000 },
];

export const designations: Designation[] = [
  { title: "Senior Frontend Engineer", department: "Engineering", level: "L4", employees: 8 },
  { title: "Product Manager", department: "Operations", level: "L5", employees: 6 },
  { title: "HR Business Partner", department: "Human Resources", level: "L3", employees: 4 },
  { title: "Finance Analyst", department: "Finance", level: "L3", employees: 7 },
  { title: "Customer Success Manager", department: "Customer Success", level: "L4", employees: 10 },
];

export const holidays: Holiday[] = [
  { name: "Independence Day", date: "2026-08-15", type: "National" },
  { name: "Founders Day", date: "2026-09-12", type: "Company" },
  { name: "Diwali", date: "2026-11-08", type: "Festival" },
  { name: "Year End Break", date: "2026-12-25", type: "Company" },
];

export const seedEmployees: Employee[] = [
  {
    id: "emp-1",
    employeeCode: "EMP-2026-001",
    name: "Aman Verma",
    avatar: "AV",
    email: "aman@aibos.com",
    phone: "+91 98765 43210",
    location: "Delhi, India",
    department: "Operations",
    designation: "Product Manager",
    employmentType: "Full Time",
    joiningDate: "2025-02-10",
    status: "Active",
    personalInformation: { dateOfBirth: "1996-04-12", gender: "Male", nationality: "Indian", maritalStatus: "Single" },
    contact: { address: "Connaught Place, New Delhi", emergencyContact: "+91 90000 11111" },
    skills: ["Product Strategy", "Automation", "Analytics"],
    experience: ["Product Manager at AI BOS", "Business Analyst at SaaSWorks"],
    education: ["MBA, Business Operations", "B.Tech, Computer Science"],
    documents: [
      { name: "identity-proof.pdf", type: "Identity", size: "820 KB" },
      { name: "offer-letter.pdf", type: "HR", size: "340 KB" },
    ],
    salaryDetails: { annualCtc: 3600000, monthlySalary: 300000, bank: "HDFC Bank", taxId: "ABCDE1234F" },
    performanceScore: 94,
  },
  {
    id: "emp-2",
    employeeCode: "EMP-2026-002",
    name: "Sofia Alvarez",
    avatar: "SA",
    email: "sofia@aibos.com",
    phone: "+1 415 555 0199",
    location: "San Francisco, US",
    department: "Engineering",
    designation: "Senior Frontend Engineer",
    employmentType: "Full Time",
    joiningDate: "2024-11-04",
    status: "Active",
    personalInformation: { dateOfBirth: "1993-08-19", gender: "Female", nationality: "American", maritalStatus: "Married" },
    contact: { address: "Market Street, San Francisco", emergencyContact: "+1 415 555 0140" },
    skills: ["React", "TypeScript", "Design Systems"],
    experience: ["Senior Engineer at AI BOS", "Frontend Lead at LinearApps"],
    education: ["MS, Human Computer Interaction"],
    documents: [{ name: "engineering-contract.pdf", type: "Contract", size: "1.1 MB" }],
    salaryDetails: { annualCtc: 185000, monthlySalary: 15416, bank: "Chase", taxId: "US-7782" },
    performanceScore: 91,
  },
  {
    id: "emp-3",
    employeeCode: "EMP-2026-003",
    name: "Arjun Mehta",
    avatar: "AM",
    email: "arjun@aibos.com",
    phone: "+91 98111 22334",
    location: "Mumbai, India",
    department: "Finance",
    designation: "Finance Analyst",
    employmentType: "Full Time",
    joiningDate: "2025-06-18",
    status: "On Leave",
    personalInformation: { dateOfBirth: "1991-01-22", gender: "Male", nationality: "Indian", maritalStatus: "Married" },
    contact: { address: "Bandra West, Mumbai", emergencyContact: "+91 90909 45454" },
    skills: ["FP&A", "Compliance", "Budgeting"],
    experience: ["Finance Analyst at AI BOS", "Audit Associate at FinCore"],
    education: ["CA Intermediate", "B.Com Finance"],
    documents: [{ name: "tax-declaration.pdf", type: "Finance", size: "410 KB" }],
    salaryDetails: { annualCtc: 2400000, monthlySalary: 200000, bank: "ICICI Bank", taxId: "PQRSX6789Z" },
    performanceScore: 88,
  },
  {
    id: "emp-4",
    employeeCode: "EMP-2026-004",
    name: "Maya Chen",
    avatar: "MC",
    email: "maya@aibos.com",
    phone: "+65 8123 4567",
    location: "Singapore",
    department: "Customer Success",
    designation: "Customer Success Manager",
    employmentType: "Contract",
    joiningDate: "2026-01-15",
    status: "Active",
    personalInformation: { dateOfBirth: "1994-10-08", gender: "Female", nationality: "Singaporean", maritalStatus: "Single" },
    contact: { address: "Raffles Place, Singapore", emergencyContact: "+65 8111 2222" },
    skills: ["Customer Success", "CRM", "Renewals"],
    experience: ["CSM at AI BOS", "Account Manager at CloudDesk"],
    education: ["BA, Business Management"],
    documents: [{ name: "nda.pdf", type: "Legal", size: "260 KB" }],
    salaryDetails: { annualCtc: 118000, monthlySalary: 9833, bank: "DBS", taxId: "SG-1188" },
    performanceScore: 86,
  },
];

export const seedAttendance: AttendanceRecord[] = [
  { id: "att-1", employeeId: "emp-1", date: "2026-07-18", checkIn: "09:12", checkOut: "18:04", workingHours: 8.8, status: "Present" },
  { id: "att-2", employeeId: "emp-2", date: "2026-07-18", checkIn: "08:58", workingHours: 5.4, status: "Present" },
  { id: "att-3", employeeId: "emp-3", date: "2026-07-18", workingHours: 0, status: "On Leave" },
  { id: "att-4", employeeId: "emp-4", date: "2026-07-18", workingHours: 0, status: "Absent" },
];

export const seedLeaveRequests: LeaveRequest[] = [
  { id: "leave-1", employeeId: "emp-3", type: "Sick Leave", from: "2026-07-18", to: "2026-07-20", reason: "Medical recovery", status: "Approved", approver: "Aman Verma" },
  { id: "leave-2", employeeId: "emp-2", type: "Paid Leave", from: "2026-08-05", to: "2026-08-08", reason: "Family travel", status: "Pending", approver: "HR Lead" },
];
