import type { Project } from "./projects.types";

export const projectStatuses = ["Planning", "Active", "On Hold", "Completed", "Delayed", "Archived"] as const;
export const projectPriorities = ["Low", "Medium", "High", "Critical"] as const;
export const projectCategories = ["Internal", "Client", "Product", "Operations", "Research", "Automation"];

export const seedProjects: Project[] = [
 {
 id: "p-1",
 projectName: "AI Sales Copilot",
 projectCode: "PRJ-2026-SALES",
 description: "AI assistant workflow for CRM follow-ups and pipeline summaries.",
 category: "Automation",
 priority: "High",
 status: "Active",
 progress: 82,
 startDate: "2026-07-01",
 endDate: "2026-08-12",
 budget: 120000,
 estimatedHours: 640,
 client: "Internal",
 teamMembers: ["Sneha Joshi", "Neha Reddy", "Karan Malhotra"],
 projectManager: "Rohan Kapoor",
 attachments: [{ name: "sales-copilot-spec.pdf", type: "PDF", size: "1.8 MB" }],
 notes: "Focus on CRM integration and executive summary prompts.",
 tags: ["ai", "crm", "automation"],
 isArchived: false,
 createdAt: "2026-07-01",
 updatedAt: "2026-07-18",
 },
 {
 id: "p-2",
 projectName: "Finance Automation",
 projectCode: "PRJ-2026-FIN",
 description: "Approval workflows for expenses, invoices, and operating reports.",
 category: "Operations",
 priority: "Critical",
 status: "Delayed",
 progress: 64,
 startDate: "2026-06-20",
 endDate: "2026-08-18",
 budget: 185000,
 estimatedHours: 920,
 client: "Internal",
 teamMembers: ["Vikram Nair", "Karan Malhotra"],
 projectManager: "Rajeev Khanna",
 attachments: [{ name: "finance-workflow-map.png", type: "Image", size: "900 KB" }],
 notes: "Review vendor reconciliation rules.",
 tags: ["finance", "workflow"],
 isArchived: false,
 createdAt: "2026-06-20",
 updatedAt: "2026-07-17",
 },
 {
 id: "p-3",
 projectName: "Employee Portal",
 projectCode: "PRJ-2026-HR",
 description: "HR self-service portal for onboarding, policies, and employee profiles.",
 category: "Internal",
 priority: "Medium",
 status: "Planning",
 progress: 38,
 startDate: "2026-07-22",
 endDate: "2026-09-02",
 budget: 95000,
 estimatedHours: 520,
 client: "HR",
 teamMembers: ["Ananya Iyer", "Neha Reddy"],
 projectManager: "Ananya Iyer",
 attachments: [],
 notes: "Align with profile module and RBAC permissions.",
 tags: ["hr", "portal"],
 isArchived: false,
 createdAt: "2026-07-10",
 updatedAt: "2026-07-15",
 },
 {
 id: "p-4",
 projectName: "Customer Success Hub",
 projectCode: "PRJ-2026-CS",
 description: "Workspace for customer health, renewals, and success plans.",
 category: "Client",
 priority: "High",
 status: "Completed",
 progress: 100,
 startDate: "2026-05-12",
 endDate: "2026-07-05",
 budget: 110000,
 estimatedHours: 700,
 client: "Success Team",
 teamMembers: ["Sneha Joshi", "Manager"],
 projectManager: "Manager",
 attachments: [{ name: "launch-report.pdf", type: "PDF", size: "2.3 MB" }],
 notes: "Launched with initial customer health scoring.",
 tags: ["crm", "customers"],
 isArchived: false,
 createdAt: "2026-05-12",
 updatedAt: "2026-07-05",
 },
 {
 id: "p-5",
 projectName: "Document Intelligence",
 projectCode: "PRJ-2026-DOC",
 description: "AI document classification and policy search module.",
 category: "Research",
 priority: "Low",
 status: "On Hold",
 progress: 24,
 startDate: "2026-08-01",
 endDate: "2026-10-15",
 budget: 76000,
 estimatedHours: 460,
 client: "Internal",
 teamMembers: ["Neha Reddy"],
 projectManager: "Administrator",
 attachments: [],
 notes: "Paused until backend document storage is finalized.",
 tags: ["documents", "ai"],
 isArchived: false,
 createdAt: "2026-07-14",
 updatedAt: "2026-07-18",
 },
];
